CREATE DATABASE IF NOT EXISTS car_dealership;
USE car_dealership;

CREATE TABLE IF NOT EXISTS Country_Master (
  Country_Id INT AUTO_INCREMENT PRIMARY KEY,
  Country_Name VARCHAR(120) NOT NULL,
  Country_Code VARCHAR(10) NOT NULL,
  Is_Deleted TINYINT(1) DEFAULT 0,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS State_Master (
  State_Id INT AUTO_INCREMENT PRIMARY KEY,
  Country_Id INT NOT NULL,
  State_Name VARCHAR(120) NOT NULL,
  Is_Deleted TINYINT(1) DEFAULT 0,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (Country_Id) REFERENCES Country_Master(Country_Id)
);
CREATE TABLE IF NOT EXISTS City_Master (
  City_Id INT AUTO_INCREMENT PRIMARY KEY,
  State_Id INT NOT NULL,
  City_Name VARCHAR(120) NOT NULL,
  Is_Deleted TINYINT(1) DEFAULT 0,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (State_Id) REFERENCES State_Master(State_Id)
);
CREATE TABLE IF NOT EXISTS Company_Master (
  Company_Id INT AUTO_INCREMENT PRIMARY KEY,
  Company_Name VARCHAR(150) NOT NULL,
  Country_Id INT,
  State_Id INT,
  City_Id INT,
  Address TEXT,
  Is_Active TINYINT(1) DEFAULT 1,
  Is_Deleted TINYINT(1) DEFAULT 0,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Role_Master (
  Role_Id INT AUTO_INCREMENT PRIMARY KEY,
  Role_Name VARCHAR(80) UNIQUE NOT NULL,
  Is_Deleted TINYINT(1) DEFAULT 0,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS User_Master (
  User_Id INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(80) UNIQUE NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Email VARCHAR(120) UNIQUE,
  Phone VARCHAR(20),
  Role_Id INT NOT NULL,
  Status VARCHAR(50),
  Is_Active TINYINT(1) DEFAULT 1,
  Is_Deleted TINYINT(1) DEFAULT 0,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (Role_Id) REFERENCES Role_Master(Role_Id)
);
CREATE TABLE IF NOT EXISTS Session_Master (
  Session_Id INT AUTO_INCREMENT PRIMARY KEY,
  User_Id INT NOT NULL,
  Refresh_Token CHAR(64) NOT NULL,
  Expires_At DATETIME NOT NULL,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_token (Refresh_Token),
  FOREIGN KEY (User_Id) REFERENCES User_Master(User_Id)
);
CREATE TABLE IF NOT EXISTS Role_Permissions (
  Permission_Id INT AUTO_INCREMENT PRIMARY KEY,
  Role_Id INT NOT NULL,
  Resource VARCHAR(80) NOT NULL,
  Action ENUM('create','read','update','delete') NOT NULL,
  Is_Deleted TINYINT(1) DEFAULT 0,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_role_resource_action (Role_Id, Resource, Action),
  FOREIGN KEY (Role_Id) REFERENCES Role_Master(Role_Id)
);
CREATE TABLE IF NOT EXISTS Login_History (
  Login_Id INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(80),
  Ip_Address VARCHAR(64),
  Is_Success TINYINT(1) NOT NULL,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Password_Reset_Tokens (
  Token_Id INT AUTO_INCREMENT PRIMARY KEY,
  User_Id INT NOT NULL,
  Token CHAR(64) NOT NULL,
  Expires_At DATETIME NOT NULL,
  Is_Used TINYINT(1) DEFAULT 0,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (User_Id) REFERENCES User_Master(User_Id)
);
CREATE TABLE IF NOT EXISTS Code_Header (
  Header_Id INT AUTO_INCREMENT PRIMARY KEY,
  Code_Name VARCHAR(80) UNIQUE NOT NULL,
  Description VARCHAR(255),
  Is_Deleted TINYINT(1) DEFAULT 0,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Code_Details (
  Detail_Id INT AUTO_INCREMENT PRIMARY KEY,
  Header_Id INT NOT NULL,
  Code_Value VARCHAR(80) NOT NULL,
  Code_Label VARCHAR(120) NOT NULL,
  Sort_Order INT DEFAULT 1,
  Is_Deleted TINYINT(1) DEFAULT 0,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (Header_Id) REFERENCES Code_Header(Header_Id)
);
CREATE TABLE IF NOT EXISTS Brand_Master (
  Brand_Id INT AUTO_INCREMENT PRIMARY KEY,
  Brand_Name VARCHAR(120) NOT NULL,
  Is_Active TINYINT(1) DEFAULT 1,
  Is_Deleted TINYINT(1) DEFAULT 0,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Feature_Master (
  Feature_Id INT AUTO_INCREMENT PRIMARY KEY,
  Feature_Name VARCHAR(120) NOT NULL,
  Is_Active TINYINT(1) DEFAULT 1,
  Is_Deleted TINYINT(1) DEFAULT 0,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Item_Model_Master (
  Model_Id INT AUTO_INCREMENT PRIMARY KEY,
  Brand_Id INT NOT NULL,
  Model_Name VARCHAR(120) NOT NULL,
  Is_Active TINYINT(1) DEFAULT 1,
  Is_Deleted TINYINT(1) DEFAULT 0,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (Brand_Id) REFERENCES Brand_Master(Brand_Id)
);
CREATE TABLE IF NOT EXISTS item_Details (
  Item_Id INT AUTO_INCREMENT PRIMARY KEY,
  Company_Id INT NOT NULL,
  Model_Id INT NOT NULL,
  Registration_No VARCHAR(30) UNIQUE NOT NULL,
  Make_Year SMALLINT NOT NULL,
  Registration_Year SMALLINT NOT NULL,
  Km_Driven INT NOT NULL,
  Price DECIMAL(12,2) NOT NULL,
  Color_Code VARCHAR(80),
  Owner_Count TINYINT DEFAULT 1,
  Insurance_Valid_Upto DATE NULL,
  Spare_Key TINYINT(1) DEFAULT 0,
  Status_Code VARCHAR(80) NOT NULL,
  Fuel_Type_Code VARCHAR(80) NOT NULL,
  Transmission_Code VARCHAR(80) NOT NULL,
  Is_Deleted TINYINT(1) DEFAULT 0,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_status (Status_Code),
  FOREIGN KEY (Company_Id) REFERENCES Company_Master(Company_Id),
  FOREIGN KEY (Model_Id) REFERENCES Item_Model_Master(Model_Id)
);
CREATE TABLE IF NOT EXISTS item_Images (
  Image_Id INT AUTO_INCREMENT PRIMARY KEY,
  Item_Id INT NOT NULL,
  Image_Path VARCHAR(255) NOT NULL,
  Is_Primary TINYINT(1) DEFAULT 0,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Item_Id) REFERENCES item_Details(Item_Id)
);
CREATE TABLE IF NOT EXISTS Item_Features (
  Item_Feature_Id INT AUTO_INCREMENT PRIMARY KEY,
  Item_Id INT NOT NULL,
  Feature_Id INT NOT NULL,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_item_feature (Item_Id, Feature_Id),
  FOREIGN KEY (Item_Id) REFERENCES item_Details(Item_Id),
  FOREIGN KEY (Feature_Id) REFERENCES Feature_Master(Feature_Id)
);
